fileupload/urls.py
# encoding: utf-8
from django.urls import path
from django.contrib.auth.decorators import login_required
from fileupload.views import (
        BasicVersionCreateView, BasicPlusVersionCreateView,
        jQueryVersionCreateView, AngularVersionCreateView,
        PictureCreateView, PictureDeleteView, PictureListView,
        )

app_name = "upload"

urlpatterns = [
#    path('basic/', BasicVersionCreateView.as_view(), name='upload-basic'),
#    path('basic/plus/', BasicPlusVersionCreateView.as_view(), name='upload-basic-plus'),
#    path('new/', PictureCreateView.as_view(), name='upload-new'),
    path('angular/', login_required(AngularVersionCreateView.as_view()), name='upload-angular'),
#    path('jquery-ui/', jQueryVersionCreateView.as_view(), name='upload-jquery'),
    path('delete/<int:pk>', login_required(PictureDeleteView.as_view()), name='upload-delete'),
    path('view/', login_required(PictureListView.as_view()), name='upload-view'),
]

home/urls.py
from django.urls import path
from .views import home,catadetail
app_name = "home"

urlpatterns = [
    path(r'', home,name="homepage"),
    path(r'catalogs/<int:pk>/', catadetail,name="cataposts"),
    
]

post/urls.py
from likedislike.models import LikeDislike
from .models import Post,Comment
from django.urls import path
from django.contrib.auth.decorators import login_required
from likedislike.views import VotesView
from .views import (
        PostCreate,
        PostList,
        PostUpdate,
        PostApi,
        postdetail,
        postcreate,
        postedit,
)

app_name = "post"

urlpatterns = [
#   path(r'list/', PostList.as_view(),name="post-list"),
    path(r'create/', postcreate,name="post-create"),
    path(r'<int:pk>/edit/', postedit,name="post-edit"),
    path(r'update/(?P<pk>[\w-]+)/', PostUpdate.as_view(),name="post-update"),
    path(r'detail/<int:id>/', postdetail,name="post-detail"),
    path(r'api/create/', PostApi.as_view(),name="postcreate-api"),
    path(r'api/<int:pk>/like/',login_required(VotesView.as_view(model=Post, vote_type=LikeDislike.LIKE)),name='post_like'),
    path(r'api/comment/<int:pk>/like/',login_required(VotesView.as_view(model=Comment, vote_type=LikeDislike.LIKE)),name='post_comment_like'),
]

prodct/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static,settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'ckeditor/', include('ckeditor_uploader.urls')),
    
    path(r'', include('home.urls', namespace='home')),
    path(r'post/', include('post.urls',namespace="post")),
    path(r'video/', include('video.urls',namespace="video")),
    path(r'user/', include('user.urls',namespace="user")),
    path('upload/', include('fileupload.urls',namespace="upload")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from django.conf import settings

from .views import (
        JoinFormView,
        SignUpView,
        user_posts_detail,
        user_posts_gallery,
        signup,
        profile_setting,
        user_profile,
        what_author_likes,
        who_likes_me,
        edit_profile_form,
)

from django.contrib.auth.views import logout,login
app_name = "user"

urlpatterns = [
    path(r'join/', signup,name="usersignup"),
    path(r'login/', login,{'template_name': 'user/login.html'},name="userlogin"),
    path(r'logout/', logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),

    path(r'<int:id>/posts/', user_posts_detail,name="user-posts"),
    path(r'<int:id>/gallery/', user_posts_gallery,name="user-posts-gallery"),
    path(r'setting/', profile_setting,name="profile-setting"),
    path(r'profile/', user_profile,name="user-profile"),
    path(r'who-likes-me/', who_likes_me,name="user-supporter"),
    path(r'<int:id>/edit_profile/',edit_profile_form, name="user-profile-update"),
    path(r'<int:id>/what-author-likes/', what_author_likes,name="user-like-posts"),
   
]

video/urls.py
from likedislike.models import LikeDislike
from django.urls import path,reverse
from django.contrib.auth.decorators import login_required

from likedislike.views import VotesView
from .models import Video,VideoComment
from .views import (
        VideoCreate,
        VideoList,
        VideoDetail,
)

app_name = "video"

urlpatterns = [
    path(r'list/', VideoList.as_view(),name="video-list"),
    path(r'create/', VideoCreate.as_view(),name="video-create"),
#    path(r'<int:pk>/edit/', postedit,name="post-edit"),
#    path(r'update/(?P<pk>[\w-]+)/', PostUpdate.as_view(),name="post-update"),
    path(r'detail/<int:pk>/', VideoDetail.as_view(),name="video-detail"),
#    path(r'api/create/', PostApi.as_view(),name="postcreate-api"),
    path(r'api/<int:pk>/like/',login_required(VotesView.as_view(model=Video, vote_type=LikeDislike.LIKE)),name='video_like'),
    path(r'api/comment/<int:pk>/like/',login_required(VotesView.as_view(model=VideoComment, vote_type=LikeDislike.LIKE)),name='video_comment_like'),
]

fileupload/models.py
# encoding: utf-8
from django.db import models
from django.contrib.auth.models import User


class Picture(models.Model):
    """This is a small demo using just two fields. The slug field is really not
    necessary, but makes the code simpler. ImageField depends on PIL or
    pillow (where Pillow is easily installable in a virtualenv. If you have
    problems installing pillow, use a more generic FileField instead.

    """
    owner = models.ForeignKey(User,on_delete=models.CASCADE)
    file = models.ImageField(upload_to="pictures")
    slug = models.SlugField(max_length=50, blank=True)

    def __str__(self):
        return self.file.name

    @models.permalink
    def get_absolute_url(self):
        return ('upload-new', )

    def save(self, *args, **kwargs):
        self.slug = self.file.name
        super(Picture, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        """delete -- Remove to leave file."""
        self.file.delete(False)
        super(Picture, self).delete(*args, **kwargs)

fileupload/views.py
# encoding: utf-8
import json

from django.http import HttpResponse
from django.views.generic import CreateView, DeleteView, ListView
from .models import Picture
from .response import JSONResponse, response_mimetype
from .serialize import serialize


class PictureCreateView(CreateView):
    model = Picture
    #fields = "__all__"
    fields = ["file","slug"] 

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.owner = self.request.user
        self.object.save()

        files = [serialize(self.object)]
        data = {'files': files}
        response = JSONResponse(data, mimetype=response_mimetype(self.request))
        response['Content-Disposition'] = 'inline; filename=files.json'
        return response

    def form_invalid(self, form):
        data = json.dumps(form.errors)
        return HttpResponse(content=data, status=400, content_type='application/json')

class BasicVersionCreateView(PictureCreateView):
    template_name_suffix = '_basic_form'


class BasicPlusVersionCreateView(PictureCreateView):
    template_name_suffix = '_basicplus_form'


class AngularVersionCreateView(PictureCreateView):
    template_name_suffix = '_angular_form'


class jQueryVersionCreateView(PictureCreateView):
    template_name_suffix = '_jquery_form'


class PictureDeleteView(DeleteView):
    model = Picture

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.owner == request.user:
            self.object.delete()
            response = JSONResponse(True, mimetype=response_mimetype(request))
            response['Content-Disposition'] = 'inline; filename=files.json'
            return response


class PictureListView(ListView):
    model = Picture

    def get_queryset(self):
        return Picture.objects.filter(owner=self.request.user)

    def render_to_response(self, context, **response_kwargs):
        files = [ serialize(p) for p in self.get_queryset() ]
        data = {'files': files}
        response = JSONResponse(data, mimetype=response_mimetype(self.request))
        response['Content-Disposition'] = 'inline; filename=files.json'
        return response

fileupload/templates/fileupload/picture_angular_form.html
<!DOCTYPE HTML>
<html lang="en">
<head>
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<![endif]-->
<meta charset="utf-8">
<title>jQuery File Upload Demo - AngularJS version</title>
<meta name="description" content="File Upload widget with multiple file selection, drag&amp;drop support, progress bars, validation and preview images, audio and video for AngularJS. Supports cross-domain, chunked and resumable file uploads and client-side image resizing. Works with any server-side platform (PHP, Python, Ruby on Rails, Java, Node.js, Go etc.) that supports standard HTML form file uploads.">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
<link rel="stylesheet" href="/static/css/style.css">
<link rel="stylesheet" href="/static/css/blueimp-gallery.min.css">
<link rel="stylesheet" href="/static/css/jquery.fileupload-ui.css">
<noscript><link rel="stylesheet" href="/static/css/jquery.fileupload-ui-noscript.css"></noscript>
<style>
/* Hide Angular JS elements before initializing */
.ng-cloak {
    display: none;
}
</style>
</head>
<body>
<div class="container">
<div class="row">

<nav>
<div id="jq-dropdown-1" class="jq-dropdown jq-dropdown-tip">
    <ul class="jq-dropdown-menu">
        <li><a href="{% url "user:user-profile" %}">Profile</a></li>
        <li><a href="{% url "user:user-supporter" %}">WhoLikeMe</a></li>
        <li><a href="{% url "upload:upload-angular" %}">Pictures</a></li>
        <li class="jq-dropdown-divider"></li>
        <li><a href="#">Setting</a></li>
        <li><a href="{% url "post:post-create" %}">Create Content</a></li>

    </ul>
</div>
<ul>
<br>
    <a href="/">Home</a> |
    <a href="{% url "post:post-create" %}">Post</a> |
    {% if user.is_authenticated %}
    {% load thumbnail %}
    welcome <a href="#" data-jq-dropdown="#jq-dropdown-1">{{request.user.username}}</a> |
    <a href="{% url "user:logout" %}">   ---  Logout</a>
    {% else %}
    <a href="{% url "user:usersignup" %}">Join</a> |
    <a href="{% url "user:userlogin" %}">Login</a> |
    {% endif %}
  </ul>
</nav>
</div>
</div>
<hr>

<div class="container-fluid">
        <div class="row">
                <div class="col-md-12">
                        <div class="row">
                                <div class="col-md-2">
                                </div>
                                <div class="col-md-8">
<a href={% url "video:video-list" %}>视频</a>
<a href=/catalogs/29/>二手车</a>
<a href=/catalogs/28/>房屋</a>
<a href=/catalogs/27/>签证</a>
<a href=/catalogs/26/>区块链</a>
<a href=/catalogs/25/>SEO</a>
<a href=/catalogs/24/>市场</a>
<a href=/catalogs/23/>财务</a>
<a href=/catalogs/22/>客服</a>
<a href=/catalogs/21/>技术</a>
<a href=/catalogs/20/>性福天地</a>
<a href=/catalogs/19/>英语</a>
<a href=/catalogs/18/>摄影</a>
<a href=/catalogs/17/>体育</a>
<a href=/catalogs/16/>游戏</a>
<a href=/catalogs/15/>美食</a>
<a href=/catalogs/14/>旅行</a>
<a href=/catalogs/13/>新闻</a>
<a href=/catalogs/12/>活动</a>
<a href=/catalogs/11/>求助</a>
                                </div>
                                <div class="col-md-2">
                                </div>
                        </div>
                </div>
        </div>
</div>

<hr>

<div class="container">
    <br>
    <form id="fileupload" action="." method="POST" enctype="multipart/form-data" data-ng-app="demo" data-ng-controller="DemoFileUploadController" data-file-upload="options" data-ng-class="{'fileupload-processing': processing() || loadingFiles}"> {% csrf_token %}
        <noscript><input type="hidden" name="redirect" value="http://blueimp.github.io/jQuery-File-Upload/"></noscript>
        <div class="row fileupload-buttonbar">
            <div class="col-lg-7">
                <span class="btn btn-success fileinput-button" ng-class="{disabled: disabled}">
                    <i class="glyphicon glyphicon-plus"></i>
                    <span>Add files...</span>
                    <input type="file" name="file" multiple ng-disabled="disabled">
                </span>
                <button type="button" class="btn btn-primary start" data-ng-click="submit()">
                    <i class="glyphicon glyphicon-upload"></i>
                    <span>Start upload</span>
                </button>
                <button type="button" class="btn btn-warning cancel" data-ng-click="cancel()">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancel upload</span>
                </button>
                <div class="fileupload-loading"></div>
            </div>
            <div class="col-lg-5 fade" data-ng-class="{in: active()}">
                <div class="progress progress-striped active" data-file-upload-progress="progress()"><div class="progress-bar progress-bar-success" data-ng-style="{width: num + '%'}"></div></div>
                <div class="progress-extended">&nbsp;</div>
            </div>
        </div>
        {% verbatim %}
        <table class="table table-striped files ng-cloak">
            <tr data-ng-repeat="file in queue">
                <td data-ng-switch data-on="!!file.thumbnailUrl">
                    <div class="preview" data-ng-switch-when="true">
                        <a data-ng-href="{{file.url}}" title="{{file.name}}" download="{{file.name}}" data-gallery><img data-ng-src="{{file.thumbnailUrl}}" alt=""></a>
                    </div>
                    <div class="preview" data-ng-switch-default data-file-upload-preview="file"></div>
                </td>
                <td>
                    <p class="name" data-ng-switch data-on="!!file.url">
                        <span data-ng-switch-when="true" data-ng-switch data-on="!!file.thumbnailUrl">
                            <a data-ng-switch-when="true" data-ng-href="{{file.url}}" title="{{file.name}}" download="{{file.name}}" data-gallery>{{file.name}}</a>
                            <a data-ng-switch-default data-ng-href="{{file.url}}" title="{{file.name}}" download="{{file.name}}">{{file.name}}</a>
                        </span>
                        <span data-ng-switch-default>{{file.name}}</span>
                    </p>
                    <div data-ng-show="file.error"><span class="label label-important">Error</span> {{file.error}}</div>
                </td>
                <td>
                    <p class="size">{{file.size | formatFileSize}}</p>
                    <div class="progress progress-striped active fade" data-ng-class="{pending: 'in'}[file.$state()]" data-file-upload-progress="file.$progress()"><div class="progress-bar progress-bar-success" data-ng-style="{width: num + '%'}"></div></div>
                </td>
                <td>
                    <button type="button" class="btn btn-primary start" data-ng-click="file.$submit()" data-ng-hide="!file.$submit">
                        <i class="glyphicon glyphicon-upload"></i>
                        <span>Start</span>
                    </button>
                    <button type="button" class="btn btn-warning cancel" data-ng-click="file.$cancel()" data-ng-hide="!file.$cancel">
                        <i class="glyphicon glyphicon-ban-circle"></i>
                        <span>Cancel</span>
                    </button>
                    <button data-ng-controller="FileDestroyController" type="button" class="btn btn-danger destroy" data-ng-click="file.$destroy()" data-ng-hide="!file.$destroy">
                        <i class="glyphicon glyphicon-trash"></i>
                        <span>Delete</span>
                    </button>
                </td>
            </tr>
        </table>
        {% endverbatim %}
    </form>
    <br>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Demo Notes</h3>
        </div>
        <div class="panel-body">
            <ul>
                <li>You can <strong>drag &amp; drop</strong> files from your desktop on this webpage.</li>
            </ul>
        </div>
    </div>
</div>
<div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls" data-filter=":even">
    <div class="slides"></div>
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
</div>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.1.5/angular.min.js"></script>
<script src="/static/js/vendor/jquery.ui.widget.js"></script>
<script src="/static/js/load-image.min.js"></script>
<script src="/static/js/canvas-to-blob.min.js"></script>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src="/static/js/jquery.blueimp-gallery.min.js"></script>
<script src="/static/js/jquery.iframe-transport.js"></script>
<script src="/static/js/jquery.fileupload.js"></script>
<script src="/static/js/jquery.fileupload-process.js"></script>
<script src="/static/js/jquery.fileupload-image.js"></script>
<script src="/static/js/jquery.fileupload-audio.js"></script>
<script src="/static/js/jquery.fileupload-video.js"></script>
<script src="/static/js/jquery.fileupload-validate.js"></script>
<script src="/static/js/jquery.fileupload-angular.js"></script>
<script src="/static/js/app.js"></script>
<script src="/static/js/csrf.js"></script>
<link type="text/css" rel="stylesheet" href="/static/js/jquery.dropdown.min.css" />
<script type="text/javascript" src="/static/js/jquery.dropdown.min.js"></script>

</body> 
</html>

fileupload/templates/fileupload/picture_form.html
{% extends "upload_base.html" %}
{% load upload_tags %}
{% block content %}
<div class="container">
 <ul class="nav nav-tabs">
        <li><a href="{% url "user:user-profile" %}">All Post</a></li>
        <li class="active"><a href="" %}">Photo Gallery</a></li>
        <li><a href="{% url "user:user-like-posts" request.user.id %}">Likes</a></li>
 </ul>

    <br>
    <br>
    <br>
    <!-- The file upload form used as target for the file upload widget -->
    <form id="fileupload" method="post" action="." enctype="multipart/form-data">{% csrf_token %}
        <!-- Redirect browsers with JavaScript disabled to the origin page -->
        <!--<noscript><input type="hidden" name="redirect" value="http://blueimp.github.io/jQuery-File-Upload/"></noscript>-->
        <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
        <div class="row fileupload-buttonbar">
            <div class="col-lg-7">
                <!-- The fileinput-button span is used to style the file input field as button -->
                <span class="btn btn-success fileinput-button">
                    <i class="glyphicon glyphicon-plus"></i>
                    <span>Add files...</span>
                    <input type="file" name="file" multiple>
                </span>
                <button type="submit" class="btn btn-primary start">
                    <i class="glyphicon glyphicon-upload"></i>
                    <span>Start upload</span>
                </button>
                <button type="reset" class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancel upload</span>
                </button>
                <button type="button" class="btn btn-danger delete">
                    <i class="glyphicon glyphicon-trash"></i>
                    <span>Delete</span>
                </button>
                <input type="checkbox" class="toggle">
                <!-- The loading indicator is shown during file processing -->
                <span class="fileupload-loading"></span>
            </div>
            <!-- The global progress information -->
            <div class="col-lg-5 fileupload-progress fade">
                <!-- The global progress bar -->
                <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                    <div class="progress-bar progress-bar-success" style="width:0%;"></div>
                </div>
                <!-- The extended global progress information -->
                <div class="progress-extended">&nbsp;</div>
            </div>
        </div>
        <!-- The table listing the files available for upload/download -->
        <table role="presentation" class="table table-striped"><tbody class="files"></tbody></table>
    </form>
    <br>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Demo Notes</h3>
        </div>
        <div class="panel-body">
            <ul>
                <li>You can <strong>drag &amp; drop</strong> files from your desktop on this webpage (see <a href="https://github.com/blueimp/jQuery-File-Upload/wiki/Browser-support">Browser support</a>).</li>
            </ul>
        </div>
    </div>
</div>
<!-- The blueimp Gallery widget -->
<div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls" data-filter=":even">
    <div class="slides"></div>
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
</div>
{% upload_js %}

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<!-- The jQuery UI widget factory, can be omitted if jQuery UI is already included -->
<script src="/static/js/vendor/jquery.ui.widget.js"></script>
<!-- The Templates plugin is included to render the upload/download listings -->
<script src="/static/js/tmpl.min.js"></script>
<!-- The Load Image plugin is included for the preview images and image resizing functionality -->
<script src="/static/js/load-image.min.js"></script>
<!-- The Canvas to Blob plugin is included for image resizing functionality -->
<script src="/static/js/canvas-to-blob.min.js"></script>
<!-- Bootstrap JS is not required, but included for the responsive demo navigation -->
<script src="/static/js/bootstrap.min.js"></script>
<!-- blueimp Gallery script -->
<script src="/static/js/jquery.blueimp-gallery.min.js"></script>
<!-- The Iframe Transport is required for browsers without support for XHR file uploads -->
<script src="/static/js/jquery.iframe-transport.js"></script>
<!-- The basic File Upload plugin -->
<script src="/static/js/jquery.fileupload.js"></script>
<!-- The File Upload processing plugin -->
<script src="/static/js/jquery.fileupload-process.js"></script>
<!-- The File Upload image preview & resize plugin -->
<script src="/static/js/jquery.fileupload-image.js"></script>
<!-- The File Upload audio preview plugin -->
<script src="/static/js/jquery.fileupload-audio.js"></script>
<!-- The File Upload video preview plugin -->
<script src="/static/js/jquery.fileupload-video.js"></script>
<!-- The File Upload validation plugin -->
<script src="/static/js/jquery.fileupload-validate.js"></script>
<!-- The File Upload user interface plugin -->
<script src="/static/js/jquery.fileupload-ui.js"></script>
<!-- The main application script -->
<script src="/static/js/main.js"></script>
<script src="/static/js/locale.js"></script>
<script src="/static/js/csrf.js"></script>
<!-- The XDomainRequest Transport is included for cross-domain file deletion for IE8+ -->
<!--[if gte IE 8]>
<script src="/static/js/cors/jquery.xdr-transport.js"></script>
<![endif]-->
{% endblock %}