home/urls.py
from django.urls import path
from .views import home,catadetail
app_name = "home"

urlpatterns = [
    path(r'', home,name="homepage"),
    path(r'catalogs/<int:pk>/', catadetail,name="cataposts"),
    
]

prodct/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static,settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'ckeditor/', include('ckeditor_uploader.urls')),
    
    path(r'', include('home.urls', namespace='home')),
    path(r'post/', include('post.urls',namespace="post")),
    path(r'video/', include('video.urls',namespace="video")),
    path(r'user/', include('user.urls',namespace="user")),
    path('upload/', include('fileupload.urls',namespace="upload")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from django.conf import settings

from .views import (
        JoinFormView,
        SignUpView,
        user_posts_detail,
        user_posts_gallery,
        signup,
        profile_setting,
        user_profile,
        what_author_likes,
        who_likes_me,
        edit_profile_form,
)

from django.contrib.auth.views import logout,login
app_name = "user"

urlpatterns = [
    path(r'join/', signup,name="usersignup"),
    path(r'login/', login,{'template_name': 'user/login.html'},name="userlogin"),
    path(r'logout/', logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),

    path(r'<int:id>/posts/', user_posts_detail,name="user-posts"),
    path(r'<int:id>/gallery/', user_posts_gallery,name="user-posts-gallery"),
    path(r'setting/', profile_setting,name="profile-setting"),
    path(r'profile/', user_profile,name="user-profile"),
    path(r'who-likes-me/', who_likes_me,name="user-supporter"),
    path(r'<int:id>/edit_profile/',edit_profile_form, name="user-profile-update"),
    path(r'<int:id>/what-author-likes/', what_author_likes,name="user-like-posts"),
   
]

video/urls.py
from likedislike.models import LikeDislike
from django.urls import path,reverse
from django.contrib.auth.decorators import login_required

from likedislike.views import VotesView
from .models import Video,VideoComment
from .views import (
        VideoCreate,
        VideoList,
        VideoDetail,
)

app_name = "video"

urlpatterns = [
    path(r'list/', VideoList.as_view(),name="video-list"),
    path(r'create/', VideoCreate.as_view(),name="video-create"),
#    path(r'<int:pk>/edit/', postedit,name="post-edit"),
#    path(r'update/(?P<pk>[\w-]+)/', PostUpdate.as_view(),name="post-update"),
    path(r'detail/<int:pk>/', VideoDetail.as_view(),name="video-detail"),
#    path(r'api/create/', PostApi.as_view(),name="postcreate-api"),
    path(r'api/<int:pk>/like/',login_required(VotesView.as_view(model=Video, vote_type=LikeDislike.LIKE)),name='video_like'),
    path(r'api/comment/<int:pk>/like/',login_required(VotesView.as_view(model=VideoComment, vote_type=LikeDislike.LIKE)),name='video_comment_like'),
]

video/models.py
from django.db import models
from django.contrib.auth.models import User
from likedislike.models import LikeDislike
from django.contrib.contenttypes.fields import GenericRelation
from django.urls import reverse

from catalog.models import Catalog
import datetime

# Create your models here.
class Video(models.Model):
    title = models.CharField(max_length=100,verbose_name="video name")
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    iframe = models.CharField(max_length=500)
    votes  = GenericRelation(LikeDislike, related_query_name='video')
    catalog             = models.ForeignKey(Catalog, blank=False, on_delete=models.CASCADE,verbose_name="select catalog")
    img                 = models.ImageField(max_length=100,upload_to='video/image/%Y/%m', default='video/image/muli.jpg', verbose_name='A picture for your video')
    draft               = models.BooleanField(default=False)
    publish             = models.DateField(auto_now=False, auto_now_add=False,default=datetime.date.today)
    watch_time           = models.IntegerField(default=0)
    updated             = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp           = models.DateTimeField(auto_now=False, auto_now_add=True)
    def __str__(self):
        return self.title

    def get_absolute_url(self):
       return reverse('video:video-detail', kwargs={'pk':self.pk})

class VideoComment(models.Model):
    content = models.TextField()
    video = models.ForeignKey(Video,on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    votes  = GenericRelation(LikeDislike, related_query_name='comment_video')
    parent = models.ForeignKey('self',blank=True, null=True,on_delete=models.CASCADE)
    created_time = models.DateTimeField(auto_now_add=True)
    last_modify_time = models.DateTimeField(auto_now=True)
    class Meta:
        ordering = ['created_time']
        verbose_name = 'comment_video'
        verbose_name_plural = verbose_name
    def __str__(self):
        return "%s's Comment" % self.author.username

video/forms.py
from .models import Video,VideoComment

from django import forms

class VideoCreateForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = [
                 "title",
                 "iframe",
                 "catalog",
                 "img",
              ]

#    def __init__(self, *args, **kwargs):
#        super(CommentForm, self).__init__(*args, **kwargs)
#        self['content'].field.widget.attrs['rows'] = 5
#        self['content'].field.widget.attrs['size'] = 5
#        self['parent'].field.widget = forms.HiddenInput()
#    def clean_content(self):
#        data =  self.cleaned_data['content']
#        if len(data) > 500:
#            raise forms.ValidationError("Comment short be shorter")
#        return data
class CommentForm(forms.ModelForm):
    class Meta:
        model = VideoComment
        fields = [
            'content',
            'parent'
        ]

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self['content'].field.widget.attrs['rows'] = 5
        self['content'].field.widget.attrs['size'] = 5
        self['parent'].field.widget = forms.HiddenInput()
    def clean_content(self):
        data =  self.cleaned_data['content']
        if len(data) > 500:
            raise forms.ValidationError("Comment short be shorter")
        return data

video/views.py
#!coding:utf-8
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.views.generic import CreateView,ListView
from django.views.generic.edit import UpdateView
from django.views.generic import FormView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect  
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.contrib import messages

from .forms import VideoCreateForm,CommentForm
from .models import Video

from rest_framework.generics import ListCreateAPIView, RetrieveUpdateDestroyAPIView
from rest_framework.views import APIView
#from .permissions import IsOwnerOrReadOnly
#from .serializers import PostSerializer



class VideoCreate(LoginRequiredMixin,FormView):
    login_url = '/user/login/'
    form_class =  VideoCreateForm 
    template_name = "video/video_create_form.html"  
    #success_url = "/video/list/"
    success_url = "/"

    def form_invalid(self, form):
        return  super().form_invalid(form)

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.save()
        return   super().form_valid(form)
#class PostUpdate(UpdateView):
#    model = Post
#    template_name = "post/post_update.html"
#    form_class = PostForm 
#    fields = ['title','content','catalog','img']
#    def get_object(self, queryset=None):
#        obj = Post.objects.get(id=self.kwargs['id'])
#        return obj

class VideoList(ListView):
    model = Video
    context_object_name = 'videos'
    queryset = Video.objects.all()
    paginate_by = 20
    template_name = "Video/video_list.html"

class VideoDetail(DetailView):
    model = Video
    template_name = 'video/video_detail.html'
    context_object_name = "video"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = CommentForm
        context['recommend_videos'] = Video.objects.order_by('?')[:10]
        return context

    def post(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            form = CommentForm(request.POST or None)
            if form.is_valid():
                comment = form.save(commit=False)
                comment.author = request.user
                comment.video =  self.get_object()
                comment.save()
                return HttpResponseRedirect(reverse("video:video-detail",args=[self.get_object().id]))

templates/video/video_create_form.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap %}
{% block title%}<title>视频发布</title>{% endblock %}
{% block content %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<form action="." method="POST" enctype="multipart/form-data">{% csrf_token %}
    {{ form | bootstrap }}
<button type="submit" class="btn btn-primary btn-sm">Create</button>
</form>
{% endblock %}

{% block custom_foot_js %}
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
{% endblock %}

templates/video/video_detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% load bootstrap  %}
{% block title %}<title>{{video.title}}</title>{% endblock %}

{% block custom_head_css_js  %}
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.11.1/build/css/alertify.min.css"/>
{% endblock %}


{% block content %}
    <p>{{ video.iframe |safe}}</p>
    <p>{{ video.title }}</p>
<p data-id="{{ video.id }}" data-type="post" data-action="like" data-object="video-like">
          <span class="glyphicon glyphicon-thumbs-up">点赞</span>
        <span  class="badge badge-light pull-right" data-count="like">{{ video.votes.likes.count }}</span>
    </p>
<hr><br>

  {% for comment in video.videocomment_set.all %}
<div class="card text-left">
  <div class="card-header">
 <a href="{% url "user:user-posts" comment.author.id %}">
 <img src="{% thumbnail comment.author.profile.picture 30x30 crop %}"/>
 </a>
 <a href="{% url "user:user-posts" comment.author.id %}" >{{ comment.author.username }}</a>
 评论于 <time datetime="{{ comment.created_time }}" title="{{ comment.created_time | date:'Y-m-d H:i:s' }}">{{ comment.created_time | timesince }}</time> 前
 <a href="javascript:reply('{{ comment.id | escapejs }}', '{{ comment.content | truncatechars:20 | escapejs }}');">回复</a>
  </div>
  <div class="card-body">
    <p class="card-text breakword">
          {% if comment.parent %}
           <blockquote><h6>回复 {{ comment.parent.author.username }} 的评论 “{{ comment.parent.content | truncatechars:50 }}”</h6></blockquote>
          {% endif %}
          <p>{{ comment.content | linebreaksbr }}</p>
    </p>
  </div>
</div>
    <p data-id="{{ comment.id }}" data-type="post" data-action="like" data-object="comment-like">
       <!-- <span class="glyphicon glyphicon-thumbs-up"></span>-->
         <span class="glyphicon glyphicon-thumbs-up"></span> Like
        <span  class="badge badge-light pull-right" data-count="like">{{comment.votes.likes.count}}</span>
    </p>
<hr>
  {% endfor %}
{% if user.is_authenticated %}
  <div id="comdiv"></div>
 <form class="comment-form-ajax" id="comment-form-id" method="post"> 
	{{ comment_form | bootstrap }}
        <button type="submit" class="btn-default btn-block btn-xs margin-top">提交</button>
	{% csrf_token %}
</form>
{% else %}
You need<a href={% url "user:userlogin" %}>Login </a> First
{% endif %}
{% endblock %}

{% block content_right %}

<h4>recommand vidoes </h4><br>

{% for video in recommend_videos %}
<div class="paragraphs">
  <div class="row">
    <div class="span4">
      <div class="clearfix content-heading">
          <img class="pull-left gap-left" src="{% thumbnail video.img 100x100 crop %}"/>
          <h5>  {{video.title|truncatechars:30}}</h5>
          <h5>  {{video.author.username}}</h5>
         <a href="{% url "video:video-detail" video.id %}" ><button class="btn btn-outline-light btn-sm ">  More</button></a>
      </div>
    </div>
  </div>
</div>
<br>
{% endfor %}
{% endblock %}

{% block custom_foot_js %} 
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="//cdn.jsdelivr.net/npm/alertifyjs@1.11.1/build/alertify.min.js"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
<script>
function like(){
{% if user.is_authenticated %}
    var like = $(this);
    var pk = like.data('id');
    var action = like.data('action');
    var object = like.data('object');
    if ( object == "comment-like" ){
	$.ajax({
        url : "/video/api/comment/" +  pk + "/" + action + "/",
        type : 'POST',
        data : { 'obj' : pk },
        success : function (json) {
            like.find("[data-count='like']").text(json.like_count);
            } });
        } else if ( object == "video-like" ) {
           $.ajax({
           url : "/video/api/" +  pk + "/" + action + "/",
           type : 'POST',
           data : { 'obj' : pk },
           success : function (json) {
           like.find("[data-count='like']").text(json.like_count);
        }
       });
}
{% else %}
    alertify.warning('You need login first');
{% endif %} 
    return false;
}
$(function() {
    $('[data-action="like"]').click(like);
});
</script>
<script>
function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}
var csrftoken = getCookie('csrftoken');
function csrfSafeMethod(method) {
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
$.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    }
});
</script>
<script type="text/javascript">
function escape(txt) {
    return txt && txt.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/'/g, '&#39;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}
function scrolltobutton(){document.getElementById("comdiv").scrollIntoView();}
function reply(id, touser) {
    $("#id_parent").val(id);
    scrolltobutton();
//    document.getElementById("comdiv").scrollIntoView();
}
</script>
{% endblock %}

templates/video/video_list.html
{% extends "base.html" %}
{% load thumbnail %}
{% block content %}

{% for video in videos %}
<div class="col-md-3">
<div class="card text-center">
  <div class="card-header">
  <a href={{video.get_absolute_url }}><img src="{% thumbnail video.img 150x100 crop %}"/></a>
  </div>
  <div class="card-body">
   <a href="{{ video.get_absolute_url }}" <h5 class="card-title">{{video.title | truncatechars:20}}</h5></a>
  </div>
  <div class="card-footer text-muted">
    
  </div>
</div>
<hr>
	</div>


{% endfor %}

<div class="col-md-12">
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
</div>
{% endif %}
{% endblock %}

templates/video/video_update_form.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap %}

{% block content %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<form action="." method="POST" enctype="multipart/form-data">{% csrf_token %}
    {{ form | bootstrap }}
<button type="submit" class="btn btn-primary btn-sm">Create</button>
</form>
{% endblock %}

{% block custom_foot_js %}
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
{% endblock %}