fileupload/urls.py
# encoding: utf-8
from django.urls import path
from django.contrib.auth.decorators import login_required
from fileupload.views import (
        BasicVersionCreateView, BasicPlusVersionCreateView,
        jQueryVersionCreateView, AngularVersionCreateView,
        PictureCreateView, PictureDeleteView, PictureListView,
        )

app_name = "upload"

urlpatterns = [
#    path('basic/', BasicVersionCreateView.as_view(), name='upload-basic'),
#    path('basic/plus/', BasicPlusVersionCreateView.as_view(), name='upload-basic-plus'),
#    path('new/', PictureCreateView.as_view(), name='upload-new'),
    path('angular/', login_required(AngularVersionCreateView.as_view()), name='upload-angular'),
#    path('jquery-ui/', jQueryVersionCreateView.as_view(), name='upload-jquery'),
    path('delete/<int:pk>', login_required(PictureDeleteView.as_view()), name='upload-delete'),
    path('view/', login_required(PictureListView.as_view()), name='upload-view'),
]

home/urls.py
from django.urls import path
from .views import home,catadetail
app_name = "home"

urlpatterns = [
    path(r'', home,name="homepage"),
    path(r'catalogs/<int:pk>/', catadetail,name="cataposts"),
    
]

post/urls.py
from likedislike.models import LikeDislike
from .models import Post,Comment
from django.urls import path
from django.contrib.auth.decorators import login_required
from likedislike.views import VotesView
from .views import (
        PostCreate,
        PostList,
        PostUpdate,
        PostApi,
        postdetail,
        postcreate,
        postedit,
)

app_name = "post"

urlpatterns = [
#   path(r'list/', PostList.as_view(),name="post-list"),
    path(r'create/', postcreate,name="post-create"),
    path(r'<int:pk>/edit/', postedit,name="post-edit"),
    path(r'update/(?P<pk>[\w-]+)/', PostUpdate.as_view(),name="post-update"),
    path(r'detail/<int:id>/', postdetail,name="post-detail"),
    path(r'api/create/', PostApi.as_view(),name="postcreate-api"),
    path(r'api/<int:pk>/like/',login_required(VotesView.as_view(model=Post, vote_type=LikeDislike.LIKE)),name='post_like'),
    path(r'api/comment/<int:pk>/like/',login_required(VotesView.as_view(model=Comment, vote_type=LikeDislike.LIKE)),name='post_comment_like'),
]

prodct/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static,settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'ckeditor/', include('ckeditor_uploader.urls')),
    
    path(r'', include('home.urls', namespace='home')),
    path(r'post/', include('post.urls',namespace="post")),
    path(r'video/', include('video.urls',namespace="video")),
    path(r'user/', include('user.urls',namespace="user")),
    path('upload/', include('fileupload.urls',namespace="upload")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from django.conf import settings

from .views import (
        JoinFormView,
        SignUpView,
        user_posts_detail,
        user_posts_gallery,
        signup,
        profile_setting,
        user_profile,
        what_author_likes,
        who_likes_me,
        edit_profile_form,
)

from django.contrib.auth.views import logout,login
app_name = "user"

urlpatterns = [
    path(r'join/', signup,name="usersignup"),
    path(r'login/', login,{'template_name': 'user/login.html'},name="userlogin"),
    path(r'logout/', logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),

    path(r'<int:id>/posts/', user_posts_detail,name="user-posts"),
    path(r'<int:id>/gallery/', user_posts_gallery,name="user-posts-gallery"),
    path(r'setting/', profile_setting,name="profile-setting"),
    path(r'profile/', user_profile,name="user-profile"),
    path(r'who-likes-me/', who_likes_me,name="user-supporter"),
    path(r'<int:id>/edit_profile/',edit_profile_form, name="user-profile-update"),
    path(r'<int:id>/what-author-likes/', what_author_likes,name="user-like-posts"),
   
]

video/urls.py
from likedislike.models import LikeDislike
from django.urls import path,reverse
from django.contrib.auth.decorators import login_required

from likedislike.views import VotesView
from .models import Video,VideoComment
from .views import (
        VideoCreate,
        VideoList,
        VideoDetail,
)

app_name = "video"

urlpatterns = [
    path(r'list/', VideoList.as_view(),name="video-list"),
    path(r'create/', VideoCreate.as_view(),name="video-create"),
#    path(r'<int:pk>/edit/', postedit,name="post-edit"),
#    path(r'update/(?P<pk>[\w-]+)/', PostUpdate.as_view(),name="post-update"),
    path(r'detail/<int:pk>/', VideoDetail.as_view(),name="video-detail"),
#    path(r'api/create/', PostApi.as_view(),name="postcreate-api"),
    path(r'api/<int:pk>/like/',login_required(VotesView.as_view(model=Video, vote_type=LikeDislike.LIKE)),name='video_like'),
    path(r'api/comment/<int:pk>/like/',login_required(VotesView.as_view(model=VideoComment, vote_type=LikeDislike.LIKE)),name='video_comment_like'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from post.models import Post

from catalog.models import Catalog

def home(request):
    catalogs = Catalog.objects.all() 
    context = {"catalogs":catalogs}
    return render(request,"home.html",context)
   
def catadetail(request,pk):
    posts_cata = get_object_or_404(Catalog,pk=pk)
    posts = posts_cata.post_set.all()
    context = {"posts":posts,"catalog":posts_cata.name}
    return render(request,"home/cata-details.html",context)

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}{% endblock %}
      <link rel="icon" type="image/ico" href="/media/ico/muli.ico">
    {% block custom_head_css_js %} {% endblock %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link type="text/css" rel="stylesheet" href="/static/js/jquery.dropdown.min.css" />
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js"></script>
    <script type="text/javascript" src="/static/js/jquery.dropdown.min.js"></script>

<style>#myBtn{display:none;position:fixed;bottom:20px;right:30px;z-index:99;font-size:18px;border:none;outline:none;background-color:red;color:#fff;cursor:pointer;padding:15px;border-radius:4px}#myBtn:hover{background-color:#555}</style>
</head>
<body>

<div class="container">
<div class="row">

<nav>
<div id="jq-dropdown-1" class="jq-dropdown jq-dropdown-tip">
    <ul class="jq-dropdown-menu">
        <li><a href="{% url "user:user-profile" %}">Profile</a></li>
        <li><a href="{% url "user:user-supporter" %}">WhoLikeMe</a></li>
        <li><a href="{% url "upload:upload-angular" %}">Pictures</a></li>
        <li class="jq-dropdown-divider"></li>
        <li><a href="#">Setting</a></li>
        <li><a href="{% url "post:post-create" %}">New Post</a></li>
        {% if request.user.is_superuser %}
        <li><a href="{% url "video:video-create" %}">New Viedeo</a></li>
        {% endif %}
        {% if request.user.is_superuser %}
        <li><a href="/admin/">Admin Dashboard</a></li>
        {% endif %}
    </ul>
</div>
<ul>
<br>
    <a href="/">Home</a> |
    <a href="{% url "post:post-create" %}">Post</a> |
    {% if user.is_authenticated %}
    {% load thumbnail %}
    welcome <a href="#" data-jq-dropdown="#jq-dropdown-1">{{request.user.username}}</a> |
    <a href="{% url "user:logout" %}">   ---  Logout</a> 
    {% else %}
    <a href="{% url "user:usersignup" %}">Join</a> |
    <a href="{% url "user:userlogin" %}">Login</a> |
    {% endif %}
  </ul>
</nav>
</div>
</div>
<hr>
<button onclick="topFunction()" id="myBtn" title="Go to top">Top</button>
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<div class="row">
				<div class="col-md-2">
				</div>
				<div class="col-md-8">
<a href={% url "video:video-list" %}>视频</a>
<a href=/catalogs/29/>二手车</a>
<a href=/catalogs/28/>房屋</a>
<a href=/catalogs/27/>签证</a>
<a href=/catalogs/26/>区块链</a>
<a href=/catalogs/25/>SEO</a>
<a href=/catalogs/24/>市场</a>
<a href=/catalogs/23/>财务</a>
<a href=/catalogs/22/>客服</a>
<a href=/catalogs/21/>技术</a>
<a href=/catalogs/20/>性福天地</a>
<a href=/catalogs/19/>英语</a>
<a href=/catalogs/18/>摄影</a>
<a href=/catalogs/17/>体育</a>
<a href=/catalogs/16/>游戏</a>
<a href=/catalogs/15/>美食</a>
<a href=/catalogs/14/>旅行</a>
<a href=/catalogs/13/>新闻</a>
<a href=/catalogs/12/>活动</a>
<a href=/catalogs/11/>求助</a>
				</div>
				<div class="col-md-2">
				</div>
			</div>
		</div>
	</div>
</div>
<hr>
{% block abovecontent  %}
{% endblock %}

<div class="container-fluid">
	<div class="row">
		<div class="col-md-3 offset-sm-2">
		{% block content_left %}{% endblock %}
		</div>
		<div class="col-md-5">
		{% block content %}{% endblock %}
		</div>
		<div class="col-md-4">
		{% block content_right %}{% endblock %}
		</div>
	</div>
</div>

</body>
<script>
window.onscroll = function() {scrollFunction()};
function scrollFunction() {
    if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
        document.getElementById("myBtn").style.display = "block";
    } else {
        document.getElementById("myBtn").style.display = "none";
    }
}

function topFunction() {
    document.body.scrollTop = 0;
    document.documentElement.scrollTop = 0;
}
</script>
{% block custom_foot_js %} {% endblock %}
</html>

templates/home.html
{% extends "base.html" %}
{% load thumbnail %}
{% load vote_counter %}
{% block title %}<title>木犁网</title>{% endblock %}
{% block custom_head_css_js %}
<style>.gap-right {margin-right: 10px;}</style>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
{% endblock %}

{% block content %}
{% for catalog in catalogs %}
{% if catalog.has_post  %}
<hr style="margin-bottom:5px !important; margin-top:5px !important; " />
<div class="row">
<h3><strong> <a href={{catalog.get_absolute_url}}>{{catalog.name}}</a></strong></h3>
</div>
{% for post in catalog.get_10_posts_for_homepage_at_most %}
<div class="paragraphs">
  <div class="row">
    <div class="span4">
      <div class="clearfix content-heading">
          <img class="pull-right gap-right" src="{% thumbnail post.img 150x100 crop %}"/>
          <h5>{{post.title|truncatechars:30}}</h5>
          <h5><a href={% url "user:user-posts" post.author.id %}>{{post.author.username}}</a>-{{post.publish}}-<i class="far fa-thumbs-up"><span class="badge">{{post|counter}}</span></i></h5>
         <a href="{% url "post:post-detail" post.id %}" ><button class="btn btn-outline-light btn-sm ">More</button></a>
      </div>
    </div>
  </div>
</div>
<br>
{% endfor %}
{% endif %}

{% endfor %}
{% endblock %}