home/urls.py
from django.urls import path
from .views import home,catadetail
app_name = "home"

urlpatterns = [
    path(r'', home,name="homepage"),
    path(r'catalogs/<int:pk>/', catadetail,name="cataposts"),
    
]

post/urls.py
from likedislike.models import LikeDislike
from .models import Post,Comment
from django.urls import path
from django.contrib.auth.decorators import login_required
from likedislike.views import VotesView
from .views import (
        PostCreate,
        PostList,
        PostUpdate,
        PostApi,
        postdetail,
        postcreate,
        postedit,
)

app_name = "post"

urlpatterns = [
#   path(r'list/', PostList.as_view(),name="post-list"),
    path(r'create/', postcreate,name="post-create"),
    path(r'<int:pk>/edit/', postedit,name="post-edit"),
    path(r'update/(?P<pk>[\w-]+)/', PostUpdate.as_view(),name="post-update"),
    path(r'detail/<int:id>/', postdetail,name="post-detail"),
    path(r'api/create/', PostApi.as_view(),name="postcreate-api"),
    path(r'api/<int:pk>/like/',login_required(VotesView.as_view(model=Post, vote_type=LikeDislike.LIKE)),name='post_like'),
    path(r'api/comment/<int:pk>/like/',login_required(VotesView.as_view(model=Comment, vote_type=LikeDislike.LIKE)),name='post_comment_like'),
]

prodct/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static,settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'ckeditor/', include('ckeditor_uploader.urls')),
    
    path(r'', include('home.urls', namespace='home')),
    path(r'post/', include('post.urls',namespace="post")),
    path(r'video/', include('video.urls',namespace="video")),
    path(r'user/', include('user.urls',namespace="user")),
    path('upload/', include('fileupload.urls',namespace="upload")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from django.conf import settings

from .views import (
        JoinFormView,
        SignUpView,
        user_posts_detail,
        user_posts_gallery,
        signup,
        profile_setting,
        user_profile,
        what_author_likes,
        who_likes_me,
        edit_profile_form,
)

from django.contrib.auth.views import logout,login
app_name = "user"

urlpatterns = [
    path(r'join/', signup,name="usersignup"),
    path(r'login/', login,{'template_name': 'user/login.html'},name="userlogin"),
    path(r'logout/', logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),

    path(r'<int:id>/posts/', user_posts_detail,name="user-posts"),
    path(r'<int:id>/gallery/', user_posts_gallery,name="user-posts-gallery"),
    path(r'setting/', profile_setting,name="profile-setting"),
    path(r'profile/', user_profile,name="user-profile"),
    path(r'who-likes-me/', who_likes_me,name="user-supporter"),
    path(r'<int:id>/edit_profile/',edit_profile_form, name="user-profile-update"),
    path(r'<int:id>/what-author-likes/', what_author_likes,name="user-like-posts"),
   
]

user/models.py
from django.db import models

from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    bio = models.TextField(max_length=500,blank=True)
    picture = models.ImageField(upload_to='avator/image/%Y/%m', default='users/image/default_avatar.png', verbose_name='Set avator')
    def __str__(self):
        return self.user.username

@receiver(post_save,sender=User)
def create_user_profile(sender,instance,created,**kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

user/forms.py
from django import forms
from .models import Profile

class JoinForm(forms.Form): # or forms.ModelForm
    email = forms.EmailField()
    name = forms.CharField(max_length=120)
    def clean_email(self):
        email = self.cleaned_data["email"]
        if "gmail" in email:
            raise forms.ValidationError("gmail is not allow to register")
        return email
        
class EditProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["bio","picture"]

user/views.py
from django.http import HttpResponse,JsonResponse,HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.views import View
from django.shortcuts import render,get_object_or_404
from django.contrib.auth import authenticate,login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import redirect
from django.urls import reverse

from post.models import Post
from .models import Profile
from .forms import EditProfileForm
from likedislike.models import LikeDislike

class JoinFormView(View):
    template_name  = 'user/join_ajax.html'
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {})
    def post(self, request, *args, **kwargs):
        print("posting..now")
        print(self.request.is_ajax())
        if not self.request.is_ajax():
            print("ajax calling ...")
            username = request.POST.get('username',None)
            password = request.POST.get('password',None)
            user = authenticate(username=username, password=password)
            if user is not None:
                print("login.....ok...")
                login(request, user)
                data = {
                    'message':'ok'
                }
                return JsonResponse(data)
            else:
                data = {
                    'message':'nope'
                }
                return JsonResponse(data)
        else:
            return render(request, self.template_name, {})

class SignUpView(View):
    template_name  = 'user/signup_ajax.html'
    def get(self, request, *args, **kwargs):
        return render(request,self.template_name,{})
    def post(self, request, *args, **kwargs):
        print("about call ajax")
        if self.request.is_ajax():
            print("after check if ajax is calling...")
            username = request.POST.get('username',None)
            password = request.POST.get('password',None)
            email = request.POST.get('email',None)
            print(username,password,email)
            if username is None or password is None or email is None:
                data = {
                    'message':'errorin'
                }
                return JsonResponse(data)

            reguser, created = User.objects.get_or_create(username=username)
            if created:
                reguser.set_password(password)
                reguser.email = email
                reguser.save()
                data = {
                    'message':'ok'
                }
                return JsonResponse(data)
            else:
                data = {
                    'message':'use'
                }
                return JsonResponse(data)
        else:
            return render(request, self.template_name, {})

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/')
    else:
        form = UserCreationForm()
    return render(request, 'user/signup.html', {'form': form})

def user_posts_detail(request,id):
    author = get_object_or_404(User,pk=id)
    posts_list = author.post_set.all()
    paginator = Paginator(posts_list, 25) # Show 25 contacts per page
    page = request.GET.get('page')
    posts = paginator.get_page(page)
    context = {"author":author,"userposts":posts}
    return render(request,"user/user-posts-all.html",context)

def user_posts_gallery(request,id):
    author = get_object_or_404(User,pk=id)
    gallery_list = author.picture_set.all()
    paginator = Paginator(gallery_list, 15) # Show 25 contacts per page
    page = request.GET.get('page')
    gallerys = paginator.get_page(page)
    context = {"author":author,"gallerys":gallerys}
    return render(request,"user/user-posts-gallery.html",context)

@login_required
def user_profile(request):
    posts_list = request.user.post_set.all()
    paginator = Paginator(posts_list, 10) # Show 25 contacts per page
    page = request.GET.get('page')
    posts = paginator.get_page(page)
    context = {"author":request.user,"userposts":posts}
    return render(request,"user/user-profile-posts.html",context)

@login_required
def profile_setting(request):
    pass 

def what_author_likes(request,id):
    author = get_object_or_404(User,pk=id)
    post_likes = [get_object_or_404(Post,pk=object_id["object_id"]) \
                  for object_id in author.likedislike_set.values("object_id")]
    context = {"postlikes":post_likes,"author":author}
    return render(request,"user/user-posts-likes.html",context)

@login_required
def edit_profile_form(request,id):
    profile = get_object_or_404(Profile,pk=id)    
    if request.user == profile.user:
        if request.method == 'POST':
            form = EditProfileForm(request.POST,request.FILES,instance=profile)
            if form.is_valid() :
                form.instance.user = request.user
                form.save()
                return HttpResponseRedirect(reverse("user:user-profile"))
        context = {"form":EditProfileForm(initial={"bio":profile.bio,"picture":profile.picture})}
        return render(request,"user/user-profile-update.html",context)

@login_required
def  who_likes_me(request):
   supporters =  []
   myposts = Post.objects.filter(author=request.user)
   if myposts.exists():
        for post in myposts:
           if  post.check_who_like_this_post() is not  None:
               supporters += post.check_who_like_this_post()
   return render(request,
                 "user/user-profile-likes.html",
                  {"supporters":list(set(supporters)),"author":request.user}
                 )        

templates/user/join_ajax.html
{% extends "base.html" %}
{% load bootstrap %}

{% block custom_head_css_js %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
{% endblock %}

{% block content %}
    <div class="container">    
        <div id="loginbox" style="margin-top:50px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">                    
            <div class="panel panel-info" >
                    <div class="panel-heading">
                        <div class="panel-title">Sign In</div>
                        <div style="float:right; font-size: 80%; position: relative; top:-10px"><a href="#">Forgot password?</a></div>
                    </div>     
                    <div style="padding-top:30px" class="panel-body" >
                        <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>
                        <form class='my-ajax-form' method='POST'  id="loginform" class="form-horizontal" role="form">{% csrf_token %}
                            <div style="margin-bottom: 25px" class="input-group">
                                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                                        <input id="login-username" type="text" class="form-control" name="username" value="" placeholder="username or email">                                        
                                    </div>
                            <div style="margin-bottom: 25px" class="input-group">
                                        <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                                        <input id="login-password" type="password" class="form-control" name="password" placeholder="password">
                                    </div>
                                <div style="margin-top:10px" class="form-group">
                                    <div class="col-sm-12 controls">
                                      <!--<a id="tn-login" href="#" class="btn btn-success">Login  </a> -->
                                      <button type="submit" class="btn btn-default">Submit</button>
                                      <a id="btn-fblogin" href="#" class="btn btn-primary">Login with Facebook</a>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-12 control">
                                        <div style="border-top: 1px solid#888; padding-top:15px; font-size:85%" >
                                            Don't have an account! 
                                        <a href="/user/signup/">
                                            Sign Up Here
                                        </a>
                                        </div>
                                    </div>
                                </div>    
                            </form>     
                        </div>                     
                    </div>  
    </div>
{% endblock %}

{% block custom_foot_js %}
<script src="//cdn.jsdelivr.net/npm/alertifyjs@1.11.1/build/alertify.min.js"></script>
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.11.1/build/css/alertify.min.css"/>
<script>
$(document).ready(function(){
    var $myForm = $('.my-ajax-form')
    $myForm.submit(function(event){
        event.preventDefault()
        var $formData = $(this).serialize()
        var $thisURL = {% url 'user:userjoin' %}
        $.ajax({
            method: "POST",
            url: $thisURL,
            data: $formData,
            success: handleFormSuccess,
            error: handleFormError,
        })

    function handleFormSuccess(data, textStatus, jqXHR){
        if (data.message=="ok"){
        alertify.success("欢迎回来，愉快")
        setTimeout(function(){ window.location.href = "/post/create/"; }, 3000);}
        else {alertify.error("登陆失败")}
    }

    function handleFormError(data,jqXHR, textStatus, errorThrown){
        alertify.error(data.message)
    }
})
</script>
<script>
function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}

var csrftoken = getCookie('csrftoken');

function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
$.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    }
});
</script>
{% endblock %}

templates/user/login.html
{% extends 'base.html' %}

{% block title %}<title>LOGIN</title>{% endblock %}
{% load bootstrap %}

{% block content %}
  <h2>L-o-g-i-n</h2>
  <form method="post">
    {% csrf_token %}
    {{ form | bootstrap }}
<button class="btn btn-primary" type="submit">Login</button>
  </form>
{% endblock %}

templates/user/signup.html
{% extends "base.html" %}
{% load bootstrap %}
{% block title %}<title> SIGNUP </title>{% endblock %}

{% block content %}

  <h2>S-i-g-n-U-p</h2>
  <form method="post">
    {% csrf_token %}
    {{ form | bootstrap }}
<button class="btn btn-primary" type="submit">Signup</button>
  </form>

{% endblock %}

templates/user/signup_ajax.html
{% extends "base.html" %}
{% load bootstrap %}
{% block custom_head_css_js %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="//cdn.jsdelivr.net/npm/alertifyjs@1.11.1/build/alertify.min.js"></script>
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.11.1/build/css/alertify.min.css"/>
{% endblock %}

{% block content %}

        <div id="signupbox" style=" margin-top:50px" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <div class="panel-title">Sign Up</div>
                        </div>
                        <div class="panel-body" >
                       <form  method='POST'  data-url='{{ request.build_absolute_uri|safe }}'  class="form-horizontal signup-ajax-form" role="form">{% csrf_token %}

                                <div id="signupalert" style="display:none" class="alert alert-danger">
                                    <p>Error:</p>
                                    <span></span>
                                </div>

                                <div class="form-group">
                                    <label for="email" class="col-md-3 control-label">Email</label>
                                    <div class="col-md-9">
                                        <input type="text" class="form-control" name="email" placeholder="Email Address">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="username" class="col-md-3 control-label">User Name</label>
                                    <div class="col-md-9">
                                        <input type="text" class="form-control" name="username" placeholder="User Name">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="password" class="col-md-3 control-label" autocomplete="new-password">Password</label>
                                    <div class="col-md-9">
                                        <input type="password" class="form-control" name="password" placeholder="Password">
                                    </div>
                                </div>


                                <div class="form-group">
                                    <!-- Button -->
                                    <div class="col-md-offset-3 col-md-9">
                                        <button id="btn-signup" type="submit" class="btn btn-info"><i class="icon-hand-right"></i> &nbsp Sign Up</button>
                                        <span style="margin-left:8px;">or</span>
                                    </div>
                                </div>

                                <div style="border-top: 1px solid #999; padding-top:20px"  class="form-group">

                                    <div class="col-md-offset-3 col-md-9">
                                        <button id="btn-fbsignup" type="button" class="btn btn-primary"><i class="icon-facebook"></i>   Sign Up with Facebook</button>
                                    </div>

                                </div>



                            </form>
                         </div>
                    </div>
               </div>


<script>
$(document).ready(function(){
 var $myForm = $('.signup-ajax-form')
 $myForm.submit(function(event){
            event.preventDefault()
            var $myformData = $(this).serialize()
            var $myURL = $myForm.attr('data-url') || window.location.href
            $.ajax({
                method: "POST",
                url: $myURL,
                data: $myformData,
                success: handleFormSuccess,
                error: handleFormError,
            })
        })
    function handleFormSuccess(data, textStatus, jqXHR){
        if (data.message=="errorin"){alertify.error("不能为空")}
        else if(data.message=="use"){alertify.warning("用户已经注册")} 
        else  
           {
                   //setTimeout(function(){ window.location.href = "/user/join/"; }, 3000);}
  		    window.location.href="/user/join/"
                   alertify.success("账号创建成功，登陆")
    }

    function handleFormError(data,jqXHR, textStatus, errorThrown){
        console.log(jqXHR)
        console.log(textStatus)
        alertify.error(data.message)
    }
})
</script>
<script>
function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}

var csrftoken = getCookie('csrftoken');

function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
$.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    }
});
</script>
{% endblock content %}

templates/user/user-posts-all.html
{% extends "base.html" %}
{% block custom_head_css_js %}

{% block title %}<title> {{author.username}}-homepage </title>{% endblock %}
{% endblock %}
{% block content %}
{% load thumbnail %}

<div class="paragraphs">
  <div class="row">
    <div class="span4">
      <div class="clearfix content-heading">
          <img class="pull-right gap-right" src="{% thumbnail author.profile.picture 150x100 crop %}"/>
          <h4>{{author.username}}</h4>
          <p>{{author.profile.bio}}-</p>
      </div>
    </div>
  </div>
</div>
<hr><br>


 <ul class="nav nav-tabs">
        <li class="active"><a href="#">All Post</a></li>
        <li><a href="{% url "user:user-posts-gallery" author.id %}">Photo Gallery</a></li>
        <li><a href="{% url "user:user-like-posts" author.id %}">Likes</a></li>
 </ul>

<hr><br>
{% for post in userposts %}
<div class="col-md-12">
<div class="card" style="width: 88rem;">
  <img class="card-img-top" src="{% thumbnail post.img 1220x250 crop %}" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">{{post.publish}}</h5>
    <p class="card-text">{{post.title}}</p>
    <p><a href="{{post.get_absolute_url}}" >More</a></p>
  </div>
</div>
<hr></br>
</div>
{% endfor %}
	</div>
</div>

<div class="pagination">
    <span class="step-links">
        {% if userposts.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ userposts.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ userposts.number }} of {{ userposts.paginator.num_pages }}.
        </span>

        {% if userposts.has_next %}
            <a href="?page={{ userposts.next_page_number }}">next</a>
            <a href="?page={{ userposts.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock %}

templates/user/user-posts-gallery.html
{% extends "base.html" %}
{% load thumbnail %}

{% block custom_head_css_js %}
{% block title %}<title> {{author}}-homepage </title>{% endblock %}
{% endblock %}

{% block content %}
<div class="paragraphs">
  <div class="row">
    <div class="span4">
      <div class="clearfix content-heading">
          <img class="pull-right gap-right" src="{% thumbnail author.profile.picture 150x100 crop %}"/>
          <h4>{{author.username}}</h4>
          <p>{{author.profile.bio}}-</p>
      </div>
    </div>
  </div>
</div>
<hr><br>


 <ul class="nav nav-tabs">
        <li><a href="{% url "user:user-posts" author.id %}">All Post</a></li>
        <li class="active"><a href="#">Photo Gallery</a></li>
        <li><a href="{% url "user:user-like-posts" author.id %}">Likes</a></li>
 </ul>

<hr><br>
{% for gallery in gallerys %}
   <img src="/media/pictures/{{gallery.slug}}">
{% endfor %}

<hr><br>
<div class="pagination">
    <span class="step-links">
        {% if gallerys.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ gallerys.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ gallerys.number }} of {{ gallerys.paginator.num_pages }}.
        </span>

        {% if gallerys.has_next %}
            <a href="?page={{ gallerys.next_page_number }}">next</a>
            <a href="?page={{ gallerys.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock %}

templates/user/user-posts-likes.html
{% extends "base.html" %}
{% load thumbnail %}

{% block custom_head_css_js %}
{% block title %}<title> {{author}}-homepage </title>{% endblock %}
{% endblock %}

{% block content %}
<div class="paragraphs">
  <div class="row">
    <div class="span4">
      <div class="clearfix content-heading">
          <img class="pull-right gap-right" src="{% thumbnail author.profile.picture 150x100 crop %}"/>
          <h4>{{author.username}}</h4>
          <p>{{author.profile.bio}}-</p>
      </div>
    </div>
  </div>
</div>
<hr><br>


 <ul class="nav nav-tabs">
        <li><a href="{% url "user:user-posts" author.id %}">All Post</a></li>
        <li><a href="{% url "user:user-posts-gallery" author.id %}">Photo Gallery</a></li>
        <li class="active"><a href="#">Likes</a></li>
 </ul>

<hr><br>
{% for post in postlikes  %}
<div class="paragraphs">
  <div class="row">
    <div class="span4">
      <div class="clearfix content-heading">
          <img class="pull-right gap-right" src="{% thumbnail post.img 150x100 crop %}"/>
          <h5>{{post.title|truncatechars:50}}</h5>
          <h5><a href={% url "user:user-posts" post.author.id %}>{{post.author.username}}</a>-{{post.publish}}</h5>
         <a href="{% url "post:post-detail" post.id %}" ><button class="btn btn-outline-light btn-sm ">More</button></a>
      </div>
    </div>
  </div>
</div>
<br>
<p>{{post.title}}</p>
{% empty %}
<p> No data</p>
{% endfor %}
{% endblock %}

templates/user/user-posts.html
{% extends "base.html" %}
{% block custom_head_css_js %}

{% block title %}<title> {{author}}-homepage </title>{% endblock %}

{% endblock %}
{% block content %}
{% load thumbnail %}

 <ul class="nav nav-tabs">
        <li class="active"><a href="/upload/basic">All Post</a></li>
        <li><a href="/upload/basic/plus">Latest</a></li>
        <li><a href="/upload/new">Photo Gallery</a></li>
        <li><a href="/upload/angular">AngularJS</a></li>
        <li><a href="/upload/jquery-ui">jQuery UI</a></li>
 </ul>

<hr><br>
{% for post in userposts %}
<div class="col-md-12">
<div class="card" style="width: 88rem;">
  <img class="card-img-top" src="{% thumbnail post.img 1220x250 crop %}" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">{{post.publish}}</h5>
    <p class="card-text">{{post.title}}</p>
    <p><a href="{{post.get_absolute_url}}" >More</a></p>
  </div>
</div>
<hr></br>
</div>
{% endfor %}
	</div>
</div>

<div class="pagination">
    <span class="step-links">
        {% if userposts.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ userposts.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ userposts.number }} of {{ userposts.paginator.num_pages }}.
        </span>

        {% if userposts.has_next %}
            <a href="?page={{ userposts.next_page_number }}">next</a>
            <a href="?page={{ userposts.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock %}

templates/user/user-profile-likes.html
{% extends "base.html" %}
{% block custom_head_css_js %}

{% block title %}<title> {{author.username}}-homepage </title>{% endblock %}

{% endblock %}
{% block content %}
{% load thumbnail %}

<div class="paragraphs">
  <div class="row">
    <div class="span4">
      <div class="clearfix content-heading">
          <img class="pull-right gap-right img-circle" src="{% thumbnail author.profile.picture 150x100 crop %}"/>
          <h4>{{author.username}}</h4>
          <p>{{author.profile.bio}}-</p>
          <a href="{% url "user:user-profile-update" author.profile.id %}"><button type="button" class="btn btn-outline-info">Edit</button></a>
      </div>
    </div>
  </div>
</div>
<hr><br>


 <ul class="nav nav-tabs">
        <li><a href="{% url "user:user-profile" %}">All Post</a></li>
        <li class="active"><a href="#">Who Likes Me</a></li>
 </ul>

<hr><br>
{% for supporter in supporters %}
<div class="col-md-12">
<div class="card" style="width: 88rem;">
  <img class="card-img-top" src="{% thumbnail supporter.profile.picture 150x100 crop %}" alt="Card image cap">
  <div class="card-body">
    <h4 class="card-title">{{supporter.username}}</h4>
    <p><a href="{% url "user:user-posts" supporter.id %}" >More</a></p>
  </div>
</div>
<hr></br>
</div>
{% endfor %}
	</div>
</div>


{% endblock %}

templates/user/user-profile-posts.html
{% extends "base.html" %}
{% block custom_head_css_js %}

{% block title %}<title> {{author.username}}-homepage </title>{% endblock %}

{% endblock %}
{% block content %}
{% load thumbnail %}

<div class="paragraphs">
  <div class="row">
    <div class="span4">
      <div class="clearfix content-heading">
          <img class="pull-right gap-right img-circle" src="{% thumbnail author.profile.picture 150x100 crop %}"/>
          <h4>{{author.username}}</h4>
          <p>{{author.profile.bio}}-</p>
          <a href="{% url "user:user-profile-update" author.profile.id %}"><button type="button" class="btn btn-outline-info">Edit</button></a>
      </div>
    </div>
  </div>
</div>
<hr><br>


 <ul class="nav nav-tabs">
        <li class="active"><a href="#">All Post</a></li>
        <li><a href="{% url "user:user-supporter" %}">Who Likes Me</a></li>
 </ul>

<hr><br>
{% for post in userposts %}
<div class="col-md-12">
<div class="card" style="width: 88rem;">
  <img class="card-img-top" src="{% thumbnail post.img 1220x250 crop %}" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">{{post.publish}}</h5>
    <p class="card-text">{{post.title}}</p>
    <a href="{{post.get_absolute_url}}" >More</a> <a href={% url "post:post-edit" post.id %}>Edit</a>
  </div>
</div>
<hr></br>
</div>
{% endfor %}
	</div>
</div>

<div class="pagination">
    <span class="step-links">
        {% if userposts.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ userposts.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ userposts.number }} of {{ userposts.paginator.num_pages }}.
        </span>

        {% if userposts.has_next %}
            <a href="?page={{ userposts.next_page_number }}">next</a>
            <a href="?page={{ userposts.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock %}